=== icann/rdap-conformance-tool/validator/src/main/resources/json-schema/rdap_domain.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "domain",
  "$id": "rdap_domain.json",
  "definitions": {
    "domainClass": {
      "const": "domain",
      "errorCode": -12203
    }
  },
  "properties": {
    "objectClassName": {
      "$ref": "#/definitions/domainClass"
    },
    "handle": {
      "type": "string",
      "errorCode": -12204
    },
    "ldhName": {
      "$ref": "rdap_common.json#/definitions/ldhName"
    },
    "unicodeName": {
      "$ref": "rdap_common.json#/definitions/unicodeName"
    },
    "variants": {
      "$ref": "rdap_variants.json#"
    },
    "nameservers": {
      "type": "array",
      "items": {
        "$ref": "rdap_nameserver.json#"
      },
      "validationName": "stdRdapNameserverLookupValidation"
    },
    "secureDNS": {
      "$ref": "rdap_secureDNS.json#"
    },
    "entities": {
      "$ref": "rdap_entities.json#"
    },
    "status": {
      "$ref": "rdap_status.json#"
    },
    "port43": {
      "$ref": "rdap_port43.json#"
    },
    "publicIds": {
      "$ref": "rdap_publicIds.json#"
    },
    "events": {
      "$ref": "rdap_events.json#"
    },
    "remarks": {
      "$ref": "rdap_common.json#/definitions/remarks"
    },
    "links": {
      "$ref": "rdap_common.json#/definitions/links"
    },
    "rdapConformance": {
      "$ref": "rdap_common.json#/definitions/rdapConformance"
    },
    "lang": {
      "$ref": "rdap_common.json#/definitions/lang"
    },
    "notices": {
      "$ref": "rdap_notices.json#"
    }
  },
  "additionalProperties": false,
  "required": [
    "objectClassName",
    "ldhName"
  ],
  "links": [
    {
      "description": "Get domain",
      "href": "/domain/{domainName}",
      "hrefSchema": {
        "properties": {
          "domainName": {
            "$ref": "rdap_common.json#/definitions/domainName"
          }
        }
      },
      "method": "GET",
      "rel": "self",
      "title": "domain",
      "targetSchema": {
        "$ref": "#"
      }
    }
  ],
  "stdRdapLdhNameValidation": -12205,
  "stdRdapUnicodeNameValidation": -12206,
  "stdRdapVariantsValidation": -12207,
  "stdRdapNameserverLookupValidation": -12208,
  "stdRdapSecureDnsValidation": -12209,
  "stdRdapEntitiesValidation": -12210,
  "stdRdapStatusValidation": -12211,
  "stdRdapPublicIdsValidation": -12212,
  "stdRdapRemarksValidation": -12213,
  "stdRdapLinksValidation": -12214,
  "stdRdapPort43WhoisServerValidation": -12215,
  "stdRdapEventsValidation": -12216,
  "stdRdapNoticesRemarksValidation": -12217,
  "stdRdapConformanceValidation": -12219,
  "structureInvalid": -12200,
  "unknownKeys": -12201,
  "duplicateKeys": -12202,
  "noticesTopMost": -12218,
  "validationName": "stdRdapDomainLookupValidation"
}

=== icann/rdap-conformance-tool/validator/src/test/resources/validators/profile/rdap_response/domain/entities/hhgames_com_response.json
{
  "objectClassName": "domain",
  "handle": "88133367_DOMAIN_COM-VRSN",
  "ldhName": "HHGAMES.COM",
  "links": [
    {
      "value": "https://rdap.verisign.com/com/v1/domain/HHGAMES.COM",
      "rel": "self",
      "href": "https://rdap.verisign.com/com/v1/domain/HHGAMES.COM",
      "type": "application/rdap+json"
    },
    {
      "value": "https://rdap.fabulous.com/rdap/domain/HHGAMES.COM",
      "rel": "related",
      "href": "https://rdap.fabulous.com/rdap/domain/HHGAMES.COM",
      "type": "application/rdap+json"
    }
  ],
  "status": [
    "client delete prohibited",
    "client transfer prohibited",
    "client update prohibited"
  ],
  "entities": [
    {
      "objectClassName": "entity",
      "handle": "411",
      "roles": [
        "registrar"
      ],
      "links": [
        {
          "href": "http://www.fabulous.com",
          "type": "text/html",
          "value": "https://rdap.fabulous.com/rdap/",
          "rel": "about"
        }
      ],
      "publicIds": [
        {
          "type": "IANA Registrar ID",
          "identifier": "411"
        }
      ],
      "vcardArray": [
        "vcard",
        [
          [
            "version",
            {},
            "text",
            "4.0"
          ],
          [
            "fn",
            {},
            "text",
            "Sea Wasp, LLC"
          ]
        ]
      ],
      "entities": [
        {
          "objectClassName": "entity",
          "roles": [
            "abuse"
          ],
          "vcardArray": [
            "vcard",
            [
              [
                "version",
                {},
                "text",
                "4.0"
              ],
              [
                "fn",
                {},
                "text",
                ""
              ],
              [
                "tel",
                {
                  "type": "voice"
                },
                "uri",
                "tel:+1.5045078209"
              ],
              [
                "email",
                {},
                "text",
                "abuse@fabulous.com"
              ]
            ]
          ]
        }
      ]
    }
  ],
  "events": [
    {
      "eventAction": "registration",
      "eventDate": "2002-07-04T19:15:32Z"
    },
    {
      "eventAction": "expiration",
      "eventDate": "2026-07-04T19:21:02Z"
    },
    {
      "eventAction": "last changed",
      "eventDate": "2025-04-16T04:27:20Z"
    },
    {
      "eventAction": "last update of RDAP database",
      "eventDate": "2025-08-05T15:37:05Z"
    }
  ],
  "secureDNS": {
    "delegationSigned": false
  },
  "nameservers": [
    {
      "objectClassName": "nameserver",
      "ldhName": "NS1.FABULOUS.COM"
    },
    {
      "objectClassName": "nameserver",
      "ldhName": "NS2.FABULOUS.COM"
    },
    {
      "objectClassName": "nameserver",
      "ldhName": "NS3.FABULOUS.COM"
    },
    {
      "objectClassName": "nameserver",
      "ldhName": "NS4.FABULOUS.COM"
    }
  ],
  "rdapConformance": [
    "rdap_level_0",
    "icann_rdap_technical_implementation_guide_1",
    "icann_rdap_response_profile_1"
  ],
  "notices": [
    {
      "title": "Terms of Service",
      "description": [
        "Service subject to Terms of Use."
      ],
      "links": [
        {
          "href": "https://www.verisign.com/domain-names/registration-data-access-protocol/terms-service/index.xhtml",
          "type": "text/html",
          "value": "https://rdap.verisign.com/com/v1/domain/hhgames.com",
          "rel": "terms-of-service"
        }
      ]
    },
    {
      "title": "Status Codes",
      "description": [
        "For more information on domain status codes, please visit https://icann.org/epp"
      ],
      "links": [
        {
          "href": "https://icann.org/epp",
          "type": "text/html"
        }
      ]
    },
    {
      "title": "RDDS Inaccuracy Complaint Form",
      "description": [
        "URL of the ICANN RDDS Inaccuracy Complaint Form: https://icann.org/wicf"
      ],
      "links": [
        {
          "href": "https://icann.org/wicf",
          "type": "text/html",
          "value": "https://rdap.verisign.com/com/v1/domain/hhgames.com",
          "rel": "help"
        }
      ]
    }
  ]
}

=== icann/rdap-conformance-tool/validator/src/test/resources/dataset/ipv6-test-data.json
{
  "rdapConformance" : [ "icann_rdap_response_profile_1", "icann_rdap_technical_implementation_guide_1", "rdap_level_0" ],
  "notices" : [ {
    "title" : "Terms of Use",
    "description" : [ "RDAP Terms of Use(.JPRS)" ],
    "links" : [ {
      "value" : "https://rdap.nic.jprs/rdap/domain/nic.jprs",
      "rel" : "terms-of-service",
      "type" : "text/html",
      "href" : "https://www.rdap.nic.jprs/docs/terms_of_use.html"
    } ]
  } ],
  "objectClassName" : "domain",
  "ldhName" : "nic.jprs",
  "nameservers" : [ {
    "objectClassName" : "nameserver",
    "ldhName" : "ns1.nic.jprs",
    "ipAddresses" : {
      "v4" : [ "202.11.16.49" ],
      "v6" : [ "2001:df0:8::a153" ]
    }
  }, {
    "objectClassName" : "nameserver", 
    "ldhName" : "ns2.nic.jprs",
    "ipAddresses" : {
      "v4" : [ "202.11.16.59" ],
      "v6" : [ "2001:df0:8::a253" ]
    }
  } ]
}

=== icann/rdap-conformance-tool/validator/src/test/resources/validators/profile/rdap_response/technical/technical_voice_array_type.json
{
  "rdapConformance": [
    "rdap_level_0",
    "icann_rdap_technical_implementation_guide_0",
    "icann_rdap_response_profile_0"
  ],
  "objectClassName": "domain",
  "ldhName": "example.com",
  "entities": [
    {
      "objectClassName": "entity",
      "handle": "TECH-123",
      "roles": [
        "technical"
      ],
      "vcardArray": [
        "vcard",
        [
          [
            "version",
            {},
            "text",
            "4.0"
          ],
          [
            "fn",
            {},
            "text",
            "Technical Contact"
          ],
          [
            "org",
            {},
            "text",
            "Example Technical Corp"
          ],
          [
            "adr",
            {},
            "text",
            [
              "",
              "Suite 500",
              "123 Tech Street",
              "San Francisco",
              "CA",
              "94105",
              "US"
            ]
          ],
          [
            "email",
            {},
            "text",
            "tech@example.com"
          ],
          [
            "tel",
            {
              "type": ["voice", "work"]
            },
            "uri",
            "tel:+1-555-555-1234"
          ],
          [
            "tel",
            {
              "type": "fax"
            },
            "uri",
            "tel:+1-555-555-5678"
          ]
        ]
      ]
    },
    {
      "objectClassName": "entity",
      "handle": "REG-456",
      "roles": [
        "registrant"
      ],
      "vcardArray": [
        "vcard",
        [
          [
            "version",
            {},
            "text",
            "4.0"
          ],
          [
            "fn",
            {},
            "text",
            "Registrant Name"
          ]
        ]
      ]
    }
  ],
  "remarks": [
    {
      "title": "Test Case",
      "description": [
        "This JSON demonstrates a technical entity with a valid voice tel property",
        "The type parameter is an array [\"voice\", \"work\"] which is valid per vCard spec",
        "This should NOT trigger -65100 error since voice tel IS present"
      ]
    }
  ]
}

=== icann/rdap-conformance-tool/validator/src/test/resources/validators/domain/private_ipv4_nameserver_bug.json
{
  "objectClassName": "domain",
  "handle": "HHGAMES.COM_DOMAIN_ID-VRSN",
  "ldhName": "hhgames.com",
  "unicodeName": "hhgames.com",
  "nameservers": [
    {
      "objectClassName": "nameserver",
      "handle": "NS1.MYDNSPLANET.COM_HOST_ID-VRSN",
      "ldhName": "ns1.mydnsplanet.com",
      "ipAddresses": {
        "v4": ["10.10.1.16"]
      }
    },
    {
      "objectClassName": "nameserver",
      "handle": "NS2.MYDNSPLANET.COM_HOST_ID-VRSN",
      "ldhName": "ns2.mydnsplanet.com",
      "ipAddresses": {
        "v4": ["192.168.1.1"]
      }
    }
  ],
  "status": ["clientDeleteProhibited", "clientTransferProhibited"],
  "events": [
    {
      "eventAction": "registration",
      "eventDate": "2011-01-01T01:01:01Z"
    },
    {
      "eventAction": "last changed",
      "eventDate": "2023-01-01T01:01:01Z"
    },
    {
      "eventAction": "expiration",
      "eventDate": "2024-01-01T01:01:01Z"
    },
    {
      "eventAction": "last update of RDAP database",
      "eventDate": "2023-12-05T21:08:28Z"
    }
  ],
  "rdapConformance": ["rdap_level_0"]
}

=== icann/rdap-conformance-tool/validator/src/test/resources/validators/profile/rdap_response/domain/entities/nomeo_multi_entity_response.json
{
  "rdapConformance": [
    "rdap_level_0",
    "redacted",
    "icann_rdap_response_profile_1",
    "icann_rdap_technical_implementation_guide_1"
  ],
  "objectClassName": "domain",
  "handle": "2138514_DOMAIN_COM-EXMP",
  "ldhName": "nomeo.com",
  "unicodeName": "nomeo.com",
  "status": ["active"],
  "events": [
    {
      "eventAction": "registration",
      "eventDate": "2003-10-10T01:55:12.0Z"
    },
    {
      "eventAction": "last changed",
      "eventDate": "2025-12-18T16:30:08.57Z"
    },
    {
      "eventAction": "expiration",
      "eventDate": "2026-10-10T01:55:12.0Z"
    },
    {
      "eventAction": "last update of RDAP database",
      "eventDate": "2026-07-15T17:35:27.129Z"
    }
  ],
  "entities": [
    {
      "objectClassName": "entity",
      "handle": "2138514_DOMAIN_COM-EXMP",
      "roles": ["administrative"],
      "vcardArray": [
        "vcard",
        [
          ["version", {}, "text", "4.0"],
          ["fn", {}, "text", ""],
          ["adr", {}, "text", ["", "", "", "", "", "", ""]],
          ["contact-uri", {}, "uri", "https://example.com/contact"]
        ]
      ]
    },
    {
      "objectClassName": "entity",
      "roles": ["registrant"],
      "vcardArray": [
        "vcard",
        [
          ["version", {}, "text", "4.0"],
          ["fn", {}, "text", ""],
          ["adr", {"cc": "BE"}, "text", ["", "", "", "", "Oost Vlaanderen", "", ""]],
          ["org", {}, "text", "Kreos Services BVBA"],
          ["contact-uri", {}, "uri", "https://example.com/contact"]
        ]
      ]
    },
    {
      "objectClassName": "entity",
      "roles": ["technical"],
      "vcardArray": [
        "vcard",
        [
          ["version", {}, "text", "4.0"],
          ["fn", {}, "text", ""],
          ["adr", {}, "text", ["", "", "", "", "", "", ""]],
          ["contact-uri", {}, "uri", "https://example.com/contact"]
        ]
      ]
    },
    {
      "objectClassName": "entity",
      "handle": "2138514_DOMAIN_COM-EXMP",
      "roles": ["billing"],
      "vcardArray": [
        "vcard",
        [
          ["version", {}, "text", "4.0"],
          ["fn", {}, "text", ""],
          ["adr", {}, "text", ["", "", "", "", "", "", ""]],
          ["contact-uri", {}, "uri", "https://example.com/contact"]
        ]
      ]
    },
    {
      "objectClassName": "entity",
      "handle": "4148",
      "roles": ["registrar"],
      "publicIds": [
        {"type": "IANA Registrar ID", "identifier": "4148"}
      ],
      "vcardArray": [
        "vcard",
        [
          ["version", {}, "text", "4.0"],
          ["fn", {}, "text", "Nomeo BV"],
          ["adr", {}, "text", ["", "", "", "", "", "", ""]]
        ]
      ]
    }
  ],
  "nameservers": [
    {
      "objectClassName": "nameserver",
      "handle": "2138514_NS1_DOMAIN_COM-EXMP",
      "ldhName": "ns53.be",
      "unicodeName": "ns53.be"
    }
  ]
}

=== icann/rdap-conformance-tool/validator/src/test/resources/validators/domain/valid.json
{
  "objectClassName": "domain",
  "handle": "2138514_DOMAIN_COM-EXMP",
  "ldhName": "EXAMPLE.COM",
  "links": [
    {
      "value": "https://rdap.example.com/com/v1/domain/EXAMPLE.COM",
      "rel": "self",
      "href": "https://rdap.example.com/com/v1/domain/EXAMPLE.COM",
      "type": "application/rdap+json"
    },
    {
      "value": "https://rdap.markmonitor.com/rdap/domain/EXAMPLE.COM",
      "rel": "related",
      "href": "https://rdap.markmonitor.com/rdap/domain/EXAMPLE.COM",
      "type": "application/rdap+json"
    }
  ],
  "status": [
    "client delete prohibited",
    "client transfer prohibited",
    "client update prohibited",
    "server delete prohibited",
    "server transfer prohibited",
    "server update prohibited"
  ],
  "entities": [
    {
      "objectClassName": "entity",
      "handle": "292",
      "roles": [
        "registrar"
      ],
      "publicIds": [
        {
          "type": "IANA Registrar ID",
          "identifier": "292"
        }
      ],
      "vcardArray": [
        "vcard",
        [
          [
            "version",
            {},
            "text",
            "4.0"
          ],
          [
            "fn",
            {},
            "text",
            "Example Inc."
          ]
        ]
      ],
      "entities": [
        {
          "objectClassName": "entity",
          "handle": "292",
          "roles": [
            "abuse"
          ],
          "vcardArray": [
            "vcard",
            [
              [
                "version",
                {},
                "text",
                "4.0"
              ],
              [
                "fn",
                {},
                "text",
                ""
              ],
              [
                "tel",
                {
                  "type": "voice"
                },
                "uri",
                "tel:+1.9999999999"
              ],
              [
                "email",
                {},
                "text",
                "abusecomplaints@example.com"
              ],
              [
                "adr",
                {
                  "type": "work"
                },
                "text",
                [
                  "",
                  "Suite 1234",
                  "4321 Rue Somewhere",
                  "Quebec",
                  "QC",
                  "G1V 2M2",
                  ""
                ]
              ]
            ]
          ]
        }
      ]
    }
  ],
  "events": [
    {
      "eventAction": "registration",
      "eventDate": "1997-09-15T04:00:00Z"
    },
    {
      "eventAction": "expiration",
      "eventDate": "2028-09-14T04:00:00Z"
    },
    {
      "eventAction": "last update of RDAP database",
      "eventDate": "2021-03-18T09:24:18Z"
    }
  ],
  "secureDNS": {
    "delegationSigned": false,
    "dsData": [
      {
        "keyTag": 55204,
        "algorithm": 8,
        "digestType": 2,
        "digest": "206D88653C43D99BF4567BBD7DF9C078DB357F59AA183741024D345723052E88"
      }
    ]
  },
  "nameservers": [
    {
      "objectClassName": "nameserver",
      "ldhName": "NS1.EXAMPLE.COM",
      "handle": "2138514_NS1_DOMAIN_COM-EXMP",
      "status": ["active"]
    },
    {
      "objectClassName": "nameserver",
      "ldhName": "NS2.EXAMPLE.COM",
      "handle": "2138514_NS2_DOMAIN_COM-EXEMPLE",
      "status": ["active"]
    },
    {
      "objectClassName": "nameserver",
      "ldhName": "NS3.EXAMPLE.COM",
      "handle": "2138514_NS3_DOMAIN_COM-EXEMPLE",
      "status": ["active"]
    },
    {
      "objectClassName": "nameserver",
      "ldhName": "NS4.EXAMPLE.COM",
      "handle": "2138514_NS_DOMAIN_COM-EXEMPLE",
      "status": ["active"]
    }
  ],
  "rdapConformance": [
    "rdap_level_0",
    "icann_rdap_technical_implementation_guide_0",
    "icann_rdap_response_profile_0"
  ],
  "notices": [
    {
      "title": "Terms of Use",
      "description": [
        "Service subject to Terms of Use."
      ],
      "links": [
        {
          "href": "https://www.example.com/domain-names/registration-data-access-protocol/terms-service/index.xhtml",
          "value": "https://www.example.com/domain-names/registration-data-access-protocol/terms-service/index.xhtml",
          "rel": "terms-of-service",
          "type": "text/html"
        }
      ]
    },
    {
      "title": "Status Codes",
      "description": [
        "For more information on domain status codes, please visit https://icann.org/epp"
      ],
      "links": [
        {
          "href": "https://icann.org/epp",
          "value":  "https://icann.org/epp",
          "rel": "self",
          "type": "text/html"
        }
      ]
    },
    {
      "title": "RDDS Inaccuracy Complaint Form",
      "description": [
        "URL of the ICANN RDDS Inaccuracy Complaint Form: https://icann.org/wicf"
      ],
      "links": [
        {
          "href": "https://icann.org/wicf",
          "value": "https://icann.org/wicf",
          "rel": "self",
          "type": "text/html"
        }
      ]
    }
  ]
}
